In [8]:
import numpy as np
a= np.array([[1,2],
             [3,4]])
print(a)
print(type(a))


[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [9]:
b = np.array([[5, 6],
              [7, 8]])
print(a + b) 
# [1+5  2+6] 
# [3+7  4+8]


c = np.array([[5, 6],
              [7, 8]])
d = np.array([[1, 2],
              [3, 4]])
print(c - d)


e = np.array([[1, 2],
              [3, 4]])
print(e * 10)

[[ 6  8]
 [10 12]]
[[4 4]
 [4 4]]
[[10 20]
 [30 40]]


In [ ]:
# 행렬 곱(Matrix Multiplication)  
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # 2행3열

b = np.array([[10],
              [20],
              [30]])        # 3행1열

print(a @ b) # 결과는 2행1열
# [1×10 + 2×20 + 3×30]
# [4×10 + 5×20 + 6×30]

# 전치행렬
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)
#a*b는 원소별 곱 , 즉 scalar 곱

[[140]
 [320]]
[[1 4]
 [2 5]
 [3 6]]
